### ISSUE TITLE
Strange Behavior With Dog Element

### ISSUE THREAD

**Issue by DevonQui** [phetsims/circuit-construction-kit-common#649] opened 2021-01-11 22:47 UTC
**Test device**
MacBook Pro

**Operating System**
Big Sur 11.0.1

**Browser**
Safari

**Problem description**
This is for https://github.com/phetsims/QA/issues/587

I noticed some strange behavior when trying to get the dog "resistor" to bark. When setting the battery on the "Lab" section of the sim to 1000V and connecting a wire from the negative terminal of the battery to a dog "resistor", you can get the dog to bark without actually completing the circuit

**Steps to reproduce**
1. Open the simulation
2. Open the "Lab" section of the simulation
3. Pull out one wire component, a dog component, and the high voltage battery (lightning bolt image on it)
4. Set the battery to 1000V and connect the wire to the negative terminal (flat side of battery)
5. Connect the other side of the wire to the front paws of the dog
6. Notice how you are able to get the dog to bark and disconnect from the wire without even completing the circuit
7. Now attach the wire to the back paws of the dog and notice that the dog barks without completing the circuit and the dog doesn't disconnect itself from the wire like what happened when connecting the wire to the front paws
8. Now attach the front paws of the dog to the wire attached to the negative terminal and notice that the dog doesn't display the same behavior as in steps 5-6

**Visuals**
https://drive.google.com/file/d/1VAd3x8dTnCTwdfkiYByrLj0aC8UsmiF6/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.2.0-dev.10 2021-01-05 20:31:01 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
Language: en-us
Window: 1440x792
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment] 2021-01-11 22:54
Great discovery @DevonQui, thanks!  I'll investigate.

**Comment by DevonQui** [comment] 2021-01-11 23:12
Also noticed another case of strange behavior here...

https://drive.google.com/file/d/18VXn4aBb4pV2Grc-rx_b9Eri_oW4fBJF/view?usp=sharing

**Comment by samreid** [comment] 2021-01-12 03:09
In https://github.com/phetsims/circuit-construction-kit-common/issues/512#issuecomment-745634034 and the following commit, we added this code to trigger a bark:

```js
    const voltage = this.voltageDifferenceProperty.value;
    if ( Math.abs( voltage ) > 100 ) {
      circuit.cutVertex( this.startVertexProperty.value );
      this.isBarkingProperty.value = true;
      this.lastBarkTime = time;
    }
```

The problem is that the voltageDifference is computed like so: the voltage at each vertex is computed.  The dog start vertex is shared with the battery vertex, and hence is at 1000V.  The dog end vertex is at 0V, so it thinks the voltage drop across the dog is 1000V.  

Adding a guard to make sure any current is flowing appears to correct the problem:

```js
    if ( Math.abs( voltage ) > 100 && Math.abs( this.currentProperty.value ) >= 1E-6 ) {
      circuit.cutVertex( this.startVertexProperty.value );
      this.isBarkingProperty.value = true;
      this.lastBarkTime = time;
    }
```

However, I'm not sure whether this is a robust, general solution.  @arouinfar @ariel-phet and/or @kathy-phet can you please comment?  Do you want me to add the current guard for testing?

**Comment by kathy-phet** [comment] 2021-01-12 13:57
Sam, we shouldn't be able to really get this scenario: 

> The problem is that the voltageDifference is computed like so: the voltage at each vertex is computed. The dog start vertex is shared with the battery vertex, and hence is at 1000V. The dog end vertex is at 0V, so it thinks the voltage drop across the dog is 1000V.

It should be 0V. Perhaps, it needs a time step to realize that both ends of the dog should be at the same voltage in this situation of not a complete circuit. If you could put a delay of a timestep or two in this code, I think the behavior would be corrected by that change: 
  const voltage = this.voltageDifferenceProperty.value;
    if ( Math.abs( voltage ) > 100 ) {
      circuit.cutVertex( this.startVertexProperty.value );
      this.isBarkingProperty.value = true;
      this.lastBarkTime = time;
    }

**Comment by samreid** [comment] 2021-01-13 04:40
Great idea! I must say I'm surprised that the physics engine works like that--I outputted the dog voltages in each time step and saw:

time step 0 (before connecting battery): 0, 0 
time step 1 (after connecting battery): 1000,0
time step 2 (one step after battery connection): 0, 0

I understand the value in time step 1, as described in https://github.com/phetsims/circuit-construction-kit-common/issues/649#issuecomment-758364987.  However, I'm not sure how it gets corrected to 0,0 in time step 2, and I didn't devote time to investigating it.  I'm also wondering if we will see other side effects from this behavior, or if we should always run 2 half time steps instead of a full time step.  For now, I committed a condition that says the threshold must be exceeded for 2 time steps, and the behavior seems to be as desired.  Ready for testing and discussion.

**Comment by kathy-phet** [comment] 2021-01-13 05:45
Great. Glad the physics is working! This is what I would expect, except I wasn't sure it would happen in one timestep. Since its an open circuit it cannot maintain a voltage difference across the dog. If there is ANY voltage difference, current/electrons will shift/flow and then stop when the voltage difference is gone. 

I don't think it needs to be half time steps. What you have above seems fine to me for the behavior of the dog barking and breaking the circuit.

**Comment by ariel-phet** [comment] 2021-01-14 02:12
@samreid I reviewed on master and the behavior looks good. Checked a few other cases (like shorting the battery with the lightbulb) and everything still looked good.

**Comment by samreid** [comment] 2021-01-14 16:53
Thanks, it seems like this issue is ready to be closed.

**Closed by samreid** 2021-01-14 16:53 UTC
Labels: status:blocks-sim-publication, status:ready-for-review, type:bug, type:question
