### ISSUE TITLE
Creating small wires not handled well

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#360] opened 2017-06-06 21:43 UTC
![image](https://user-images.githubusercontent.com/13894380/26853322-c03d9740-4ace-11e7-9664-df65594982fe.png)

Wires that are adjusted to have small lengths don't expand well. The vertices overlap as well.

**Comment by samreid** [comment] 2017-06-13 16:30
Similar to #344, @arouinfar do you want to add special cases for the rules about translating away vertices that overlap?  Right now it is a rotation because that cannot disturb fixed length elements, but we could add special cases for situations like this.

**Comment by arouinfar** [comment] 2017-06-15 16:41
@samreid if the solution I proposed in https://github.com/phetsims/circuit-construction-kit-common/issues/344#issuecomment-308185781 is feasible, then perhaps we can use a similar approach for handling short wires.

**Comment by samreid** [comment] 2017-06-15 16:46
If I understood the recommendation in https://github.com/phetsims/circuit-construction-kit-common/issues/344#issuecomment-308185781 correctly, it still used a rotation, so would be unable to lengthen wires.

**Comment by arouinfar** [comment] 2017-06-15 16:48
Ok, let's talk about this issue more at design meeting @samreid.

**Comment by arouinfar** [comment] 2017-06-15 23:11
Discussed in 6/15/17 design meeting. Wire vertices should not be allowed to overlap. We discussed two possible approaches

1. Vertices cannot be dragged over one another. 
2. Allow vertices to drag over/through one another, but on release translate the vertex so it doesn't overlap.

@kathy-phet prefers option 2, but I am fine with whatever option is easiest/most stable @samreid.

**Comment by samreid** [comment] 2017-06-22 17:00
Other notes from the meeting:

shouldn't have overlapping vertices once dropped
try making it so wires have a minimum length
or when dropped it translates away

**Comment by samreid** [comment] 2017-06-28 01:36
It would be nice to reuse the cutVertex behavior for this, but that code is somewhat specialized.

**Comment by samreid** [comment] 2017-06-28 02:28
Proposed fix is in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.74/circuit-construction-kit-dc_en.html

@arouinfar can you please test it out?

**Comment by arouinfar** [comment] 2017-06-28 17:33
@samreid overall, things are working nicely! Vertex overlap can still be created when severing two short wires. Clicking on one of the short wires will cause the overlap to be corrected. I could live with this behavior, but I wanted to pass this one back to @samreid in case there is a simple solution. If not, feel free to close the issue.


![image](https://user-images.githubusercontent.com/8419308/27651126-774a1c16-5bf4-11e7-8539-a6eb0d3842d3.png)  

![image](https://user-images.githubusercontent.com/8419308/27651139-7d0374b8-5bf4-11e7-924f-1b8305087fd8.png)  

![image](https://user-images.githubusercontent.com/8419308/27651307-198608c8-5bf5-11e7-94fa-d1e66474e1fe.png)

**Comment by samreid** [comment] 2017-07-01 01:03
If we add a rule that "any time a vertex moves it will run the bump away logic" it could lead to cascades like the one we saw in https://github.com/phetsims/circuit-construction-kit-common/issues/132#issue-160071856

Would it be possible to run this logic once on moved vertices after a cut?  Perhaps.

**Comment by samreid** [comment] 2017-07-01 01:18
I tried adding this code after the cut code:

```js
        // make sure the new vertex didn't end up on top of another vertex, see
        // https://github.com/phetsims/circuit-construction-kit-common/issues/360
        var neighborCircuitElements = this.getNeighborCircuitElements( newVertex );
        if ( neighborCircuitElements.length === 1 ) {
          this.bumpAwaySingleVertex( neighborCircuitElements[ 0 ].getOppositeVertex( newVertex ), newVertex );
        }
```

But it did not have the desirable behavior.

**Comment by samreid** [comment] 2017-07-01 01:18
The root of the problem is that the cut code is putting vertices over other vertices--would be best if it could avoid that problem in the first place.

**Comment by samreid** [comment] 2017-07-01 01:26
After trying a few things, I'm not seeing a straightforward solution to this problem.  My hope is that it won't create too much confusion in the user interface--if we observe otherwise we can put more time into it.

**Closed by samreid** 2017-07-01 01:26 UTC
