### ISSUE TITLE
More wires?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#432] opened 2018-03-06 20:29 UTC
I forget how we arrived at the current wire limit (was it a performance concern on iPad 2)?

This user makes a case for circuit comparison:

https://twitter.com/MO_Keeffe/status/971114960699969536

![capture](https://user-images.githubusercontent.com/4051174/37056671-5524f390-2142-11e8-9006-f1b1d57b01e9.PNG)

**Comment by ariel-phet** [comment] 2018-03-06 20:29
@arouinfar thoughts here?

**Comment by phet-steele** [comment] 2018-03-06 20:42
Found the commit that first limited wires. Doesn't have a linked issue, but at least gives us a date to look for a discussion: April 27, 2016. https://github.com/phetsims/circuit-construction-kit-common/commit/62aa788a97eb74f8ad46d169e4e5d8c1cc23e8d7

**Comment by phet-steele** [comment] 2018-03-06 20:50
Issue that requested to bump the number up to 20: https://github.com/phetsims/circuit-construction-kit-common/issues/110.

Could be that the limit was requested for BBS?

**Comment by arouinfar** [comment] 2018-03-06 21:18
I think it would be pedagogically useful to increase the number of wires @ariel-phet. The circuits in the teacher's screenshot are quite reasonable, and are likely to be recreated by other teachers. 

I believe the initial limit may have been performance/Stanford related -- thanks for digging up the issue @phet-steele! I requested 20 wires in #110 because it was double the previous limit, but 20 is not a particularly special number. Perhaps 25 would be a better limit?

Talking to @phet-steele, longer wires = more electrons = more expensive (generally speaking). If a student has lots of long wires with electrons turned on, then there would likely be some performance hit on iPad2. That said, I think the added flexibility of increasing number of wires would be be an acceptable trade-off.

**Comment by arouinfar** [comment] 2018-03-06 21:19
How does that sound @ariel-phet?

**Comment by ariel-phet** [comment] 2018-03-06 22:47
@arouinfar sounds good to me, and my guess is an easy change.

**Comment by arouinfar** [comment] 2018-03-06 22:57
@samreid can you increase the number of wires to 25?

**Comment by samreid** [comment] 2018-03-07 03:47
Sure, do you want this published right away as a maintenance release?

**Comment by ariel-phet** [comment] 2018-03-07 06:04
I think it would be nice to publish as a maintenance release. A spot check seems appropriate.

**Comment by samreid** [comment] 2018-03-08 04:31
@mattpen am I cleared to do chipper 1.0 maintenance releases?  I know the build server has been in flux lately.

**Comment by mattpen** [comment] 2018-03-08 05:31
@samreid, I am doing all of my testing for the build-server on ox-dev.  A maintenance release should be fine.

**Comment by samreid** [comment] 2018-03-09 04:16
@ariel-phet I'm operating under the assumption that we'll make maintenance releases for both DC and Virtual Lab.  Please correct me right away if that's wrong.

**Comment by samreid** [comment] 2018-03-09 14:36
I published RC1 here:
https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.1-rc.1/circuit-construction-kit-dc_en.html
and
https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc-virtual-lab/1.0.1-rc.1/circuit-construction-kit-dc-virtual-lab_en.html

I'll open a QA issue for spot testing them.

**Comment by samreid** [comment] 2018-03-09 17:02
On hold until testing complete.

**Comment by ariel-phet** [comment] 2018-03-09 19:19
Correct assumption @samreid

**Comment by samreid** [comment] 2018-03-10 02:42
Testing passed, ready for publication.

**Comment by samreid** [comment] 2018-03-10 03:44
I'm inclined to work on this Monday in case something goes wrong.  I'll put it on my personal calendar.

**Comment by samreid** [comment] 2018-03-12 15:32
Starting 1.0.1 publication now.

**Comment by samreid** [comment] 2018-03-12 15:37
dc-1.0.1 is now visible on the website, I'll diff check it as described in https://github.com/phetsims/QA/issues/107#issuecomment-371838501

**Comment by samreid** [comment] 2018-03-12 15:56
Virtual lab published, diff looks good.

Reassigned to @ariel-phet to notify the customer/social media as appropriate.

**Comment by ariel-phet** [comment] 2018-03-12 20:56
Looks good, closing!

**Comment by oliver-phet** [comment] 2019-02-12 17:49
Another user replied asking about the limit:

> It looks like there is a number limit for the wires that can be used. After exceeding this number, the wires disappear from the item list.

> Isn't it a good idea to open the wire count and add a note, or a warning, that exceeding 20 wires might impact the simulation's performance on older devices not to deprive other devices of building more complex circuits?

**Comment by ariel-phet** [comment] 2019-02-12 18:08
@arouinfar and I discussed a little and perhaps we could try this as a query parameter such as `?extraWires` so it was not easily accessible to students but could be provided in the teacher tips or primer or such. 

Another option would be to put this option in an options menu.

@samreid how difficult would adding such a query parameter be?

**Comment by samreid** [comment] 2019-02-12 18:17
Adding a query parameter to set the max number of wires would be a very easy change. (Easier than adding an options menu).

**Comment by samreid** [comment] 2019-02-13 00:14
Perhaps it would be better to just increase the number of wires permanently, for all users.  Now that we no longer support iPad 2, performance may not be an issue.  Can we test/investigate that approach before adding query parameters? What is our new slowest supported platform?  How many wires do we want?

**Comment by arouinfar** [comment] 2019-02-14 17:56
@samreid according to https://github.com/phetsims/energy-forms-and-changes/issues/191#issuecomment-462496115, our slowest iPad above the iPad2 is Jemison (iPad 4, iOS 10). I tested the published version of CCK: DC on Jemison, and it ran pretty smoothly. When maximizing the number of wires in the play area, the frame rate dipped to 11FPS, but the sim was still pretty responsive. I didn't feel like dragging components was particularly laggy. 

![img_0004](https://user-images.githubusercontent.com/8419308/52804648-f7358c80-3041-11e9-9806-a68b28ef3dde.PNG)

Tentatively, it seems like we could increase the number of wires for all users, assuming iPad2 is no longer supported. I still think we'd want QA to test the sim a bit with a larger wire count to be sure.

As for the number of wires, I think that it will always be a bit arbitrary. Maybe we could simply double the number to 50? 

Thoughts @ariel-phet?

**Comment by samreid** [comment] 2019-02-14 20:37
For now, we would like to add a query parameter in master.   Then we'll assign to @arouinfar for testing.  May do an RC in March.  Call it something like `moreWires`.

**Comment by samreid** [comment] 2019-02-15 03:27
Added query string in the preceding commits. @arouinfar can you please test and check performance?

**Comment by arouinfar** [comment] 2019-02-18 18:15
I tested `?moreWires` in iOS 10, 11, and 12. In all cases, the frame rate will drop off when there are a lot of circuit components in the play area. For iOS 11 and 12, the performance remained pretty responsive, but things got a bit laggy (but still usable) for iOS 10. I think `?moreWires` will be perfectly fine for our supported versions of iOS.  I still need to test Chromebook, but I'll report back soon.

Jemison, iPad 4, iOS 10.3.3
![img_0006](https://user-images.githubusercontent.com/8419308/52969370-5ca0ba80-336d-11e9-8add-5ef99140105b.PNG)

Pauling, iPad Air 2, iOS 11.4.1
![img_0200](https://user-images.githubusercontent.com/8419308/52969371-5ca0ba80-336d-11e9-89e6-9069e4931a7e.PNG)

Leibniz, iPad Air 2, iOS 12.1.4
![img_1378](https://user-images.githubusercontent.com/8419308/52969372-5ca0ba80-336d-11e9-944e-befefd844e72.PNG)

**Comment by arouinfar** [comment] 2019-02-18 18:57
I tested `?moreWires` on Chadwick (ChromeOS, stable channel) and Feynman (ChromeOS, beta channel), and the performance was similar/slightly better than the iPad Air 2's.

@samreid I think we can safely move forward with `?moreWires`.

**Comment by samreid** [comment] 2019-02-24 03:27
Based on https://github.com/phetsims/circuit-construction-kit-common/issues/432#issuecomment-463785461, I'll unassign for now and put a note in my calendar to re-evaluate mid-March.

**Comment by samreid** [comment] 2019-09-16 17:57
I confirmed I was able to create 50 wires by using the published version https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html?moreWires

Closing.

**Closed by samreid** 2019-09-16 17:57 UTC
Labels: priority:3-medium, status:ready-for-review, type:user-feedback
