### ISSUE TITLE
Sensor tool icons should reflow centered layout when others are made invisible

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#925] opened 2023-01-13 18:39 UTC
If a sensor tool icon is removed via PhET-iO, the rest of the sensors should reflow so that they are center-aligned. This applied both within the sensor toolbox as well as the subset of ammeter types.

This issue was discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/917

**Comment by matthew-blackman** [comment] 2023-01-19 19:32
Things are looking good in the sensor toolbox tree and ready for @arouinfar to review. Note that @samreid and I are aware of a panel alignment issue (see screenshot below) that is exposed by removing tool nodes, but is unrelated to this issue. I will open a separate issue for this. 
<img width="290" alt="Screen Shot 2023-01-19 at 2 31 17 PM" src="https://user-images.githubusercontent.com/108756567/213541801-c2aba276-9e75-4bf0-a820-e043484b66ff.png">

**Comment by arouinfar** [comment] 2023-01-20 18:07
@matthew-blackman looks good! Seems like the AccordionBox alignment hasn't been moved to its own issue yet, so I'll leave this one open so we don't forget.

**Comment by matthew-blackman** [comment] 2023-01-23 14:29
Moved remaining panel layout issues to https://github.com/phetsims/circuit-construction-kit-common/issues/940

**Comment by matthew-blackman** [comment] 2023-01-31 18:34
While working on the featured overrides, @arouinfar and I noticed that the nonContactAmmeterToolNode does not have a visible property. It should have the same tree structure as the voltmeterToolNodes and seriesAmmeterToolNodes

**Comment by samreid** [comment] 2023-02-03 22:06
I added that, and it seems to work well in testing.  Closing.

**Comment by arouinfar** [comment] 2023-03-13 15:44
Looks like there's a regression and this is no longer fixed, as discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/987.

**Comment by matthew-blackman** [comment] 2023-03-13 16:19
The above commit appears to fix the issue for both DC and DC-VL. @arouinfar please confirm that all combos of voltmeter/ammeters visibility reflow correctly. @samreid if you can code review https://github.com/phetsims/circuit-construction-kit-common/commit/2ff682bcb5d25c5a5895a1a66d0c382bbb38d44a I think we should be able to MR this into CCK common.

**Closed** 2023-03-13 19:15 UTC
