### ISSUE TITLE
voltage number control not working properly in Studio and State Wrappers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#840] opened 2022-02-04 14:13 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/772 in the lab screen only:

In State: After building a circuit, clicking on the battery causes the voltage to change in the downstream sim. Changing the voltage in the upstream sim doesn't change the voltage in the downstream sim unless you are in the 100-120V range. 

**Steps to reproduce**
In State:
1. Go to the lab screen
2. Build a simple circuit (switch, battery, bulb) and close switch
3. Attach ammeter (either kind) and voltmeter
4. Click on the battery-- The voltage will read 100V in downstream sim
5. Change voltage using slider or increment/decrement buttons--the slider will not move and the voltage will not change in the downstream sim until the 100-120V range

In Studio:
1. Go to the lab screen
2. Build a simple circuit (switch, battery, bulb) and close switch
3. Attach ammeter (either kind) and voltmeter
4. Click on the battery
5. Launch sim--The voltage will read 100V 
If the sim is launched without the battery selected, the voltage reading is correct. 

**Visuals**
![battery](https://user-images.githubusercontent.com/87318828/152541924-c4a24711-d232-44b8-a771-8256579715a4.gif)

![batterystudio](https://user-images.githubusercontent.com/87318828/152543531-e606176f-e3ba-461f-9965-afbb406a1712.gif)

**Comment by Nancy-Salpepi** [comment] 2022-02-04 16:46
The same thing seems to be happening with resistors (both types) and lightbulbs (both types) on the lab screen in both studio and state. As with the battery, if the resistor or lightbulb is not selected when the sim is launched, it launches properly. 
![resistors](https://user-images.githubusercontent.com/87318828/152568339-1cee871d-ca91-4391-a659-da7c48b9d9a3.gif)

**Comment by KatieWoe** [comment] 2022-02-04 19:11
I'm also reproducing this by flipping the battery around and launching the sim in the lab screen.
![9to100](https://user-images.githubusercontent.com/41024075/152588870-5d234fe7-65ea-4e29-8860-a32641e01160.gif)

**Comment by arouinfar** [comment] 2022-02-07 19:50
@samreid this looks like a bug that can negatively impact the client's usage. I recommend we try fixing this before sending the client another version, but if that's not feasible it should be documented as a known bug.

**Comment by samreid** [comment] 2022-02-11 02:34
@arouinfar can you reproduce this bug?  I set up this case and saw that the value was transmitted properly:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/679486/153529184-58025244-3440-45f3-b517-decc378f2322.png">

**Comment by samreid** [comment] 2022-02-11 03:49
Thanks, that helped me reproduce and correct the problem.  Ready for next round of testing.

**Comment by samreid** [comment] 2022-02-11 05:51
Can you please test/review this on master using phettest?  Please close if it seems corrected.

**Comment by Nancy-Salpepi** [comment] 2022-02-11 13:19
Looks fixed on master.

**Comment by KatieWoe** [comment] 2022-02-14 23:05
Reopening as I managed to reproduce this in https://github.com/phetsims/qa/issues/774. It was seen with the bill, eraser, hand,  and dog. It also happened in the intro screen as well as the lab screen. It could be seen if there was a circuit, or, more easily, if values were on.
<img width="501" alt="money" src="https://user-images.githubusercontent.com/41024075/153961442-ef50f525-98ea-4101-ad4e-a83874cefb51.png">
<img width="457" alt="hand" src="https://user-images.githubusercontent.com/41024075/153961444-c7bca52c-a59b-4da2-8bd6-719d2242cb0a.png">
<img width="457" alt="dog" src="https://user-images.githubusercontent.com/41024075/153961445-30eb654c-afd7-46e5-ac0e-4e149ccf660e.png">
<img width="464" alt="eraser" src="https://user-images.githubusercontent.com/41024075/153961446-d818b2f4-7f5c-4251-a96e-58d45dfb2a10.png">

**Comment by KatieWoe** [comment] 2022-02-15 16:41
This may also happen with the non-ohmic bulb at high resistance. The value in the gif bellow seems to stutter each time state is set before going to the correct value.
![stutternumber](https://user-images.githubusercontent.com/41024075/154107527-2066dadd-fe7f-457b-b316-afc3b663438c.gif)

**Comment by samreid** [comment] 2022-02-17 20:56
Is there an uninstrumented property in the realistic bulb that has a correction step?

**Comment by samreid** [comment] 2022-11-21 19:56
@matthew-blackman and I tested this behavior, we were able to recreate the buggy behavior on the dev version listed in https://github.com/phetsims/qa/issues/774, but not in the current state of master.  @KatieWoe can you please double check on phettest?  Please close if all is well.

**Comment by KatieWoe** [comment] 2022-11-21 22:52
Something froze the downstream sim while I was attempting to test this:
<img width="955" alt="notest" src="https://user-images.githubusercontent.com/41024075/203173973-bb02b7b0-e9d5-4d16-9641-67d06c02086c.png">

**Comment by KatieWoe** [comment] 2022-11-21 23:02
When the above bug doesn't stop me, it does seem this is fixed on master.

**Comment by KatieWoe** [comment] 2022-11-21 23:10
The non-ohmic bulb now seems to read 1000 ohms no matter what the current, making that aspect hard to test. The rest of the objects (dog, etc.) seem to be fixed.

**Comment by samreid** [comment] 2022-11-22 00:04
I fixed the ammeter problem.  I'm also seeing varying values in the non-ohmic bulb

<img width="522" alt="image" src="https://user-images.githubusercontent.com/679486/203182581-9870a3ee-e2b9-481d-a7e0-875cd26ba904.png">

Can you please specify how to reproduce the problem?

**Comment by KatieWoe** [comment] 2022-11-22 15:44
I was mixing up bulbs in my previous testing, sorry. The non-ohmic bulb looks ok.

**Comment by KatieWoe** [comment] 2022-11-29 15:42
I think this can be closed.

**Closed by KatieWoe** 2022-11-29 15:42 UTC
Labels: type:bug, dev:help-wanted
