### ISSUE TITLE
Temporary loss of Current graph

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#728] opened 2021-08-30 18:36 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.4

**Browser**
chrome

**Problem description**
In the RLC screen, when the circuit below was created with the resistor set to 9.8 ohms and the capacitor to .07f, the current graph sometimes disappears while the gray pointer continues to oscillate as though current is changing. In addition, small blips are sometimes seen in the current graph. 

**Steps to reproduce**
Still working on this. Neither I nor @stemilymill could replicate at this point. 

**Visuals**
Circuit:
<img width="955" alt="Screen Shot 2021-08-30 at 12 46 25 PM" src="https://user-images.githubusercontent.com/87318828/131386514-94e6ee59-9e56-42c4-8d8f-c1a79701c860.png">

Current graph disappears:
https://drive.google.com/file/d/1JV1TFemLy-KXcD0Z7YZrbSAdX6mQIN1d/view?usp=sharing

Small blips in current:
https://drive.google.com/file/d/1Fm0VQ4mJt_MmYtywWfRY7otfREGqaheE/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: AC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.16/phet/circuit-construction-kit-ac_en_phet.html
Version: 1.0.0-dev.16 2021-08-28 01:01:15 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Language: en-US
Window: 414x219
Pixel Ratio: 6/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment] 2021-08-30 18:39
@samreid is the order in which a circuit constructed important? Just wondering why I'm having difficulty reproducing.

**Comment by samreid** [comment] 2021-08-30 20:29
There are at least 3 factors that may affect reproducibility (but which are ideally not supposed to affect reproducibility):

1. The orientation of circuit elements.  For instance, connecting the right side of a wire vs the left side of a wire is handled differently in the code.  It should be treated the same, but there may be bugs.
2. The order of connection
3. Minor adjustments in wire length changes the wire resistance (since resistance = resistivity * length)

Struggling with reproducibility of problems has been a real problem with this sim.

**Comment by samreid** [comment] 2021-08-30 21:14
I also saw the chart flickering out a few times last week, after the conversion to use canvas instead of scenery.  Hopefully @jonathanolson and I can discuss this on Wednesday.

**Comment by Nancy-Salpepi** [comment] 2021-08-30 23:22
I'm still trying to reproduce but from the same video (it was over 2 minutes), there was a time where BOTH curves disappeared. Even though I wasn't touching anything, the behavior wasn't consistent. 

https://drive.google.com/file/d/17L73cpJIisIc_D2iS9zYKL3Q842AuLj2/view?usp=sharing

**Comment by samreid** [comment] 2021-08-31 00:17
Thanks, I'll coordinate with @jonathanolson about this bug.  I don't think we need to try further to reproduce it at this time.

**Comment by samreid** [comment] 2021-08-31 20:03
We noticed that canvas context is not saved and restored in CanvasLinePlot.

**Comment by samreid** [comment] 2021-09-01 01:13
This version https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.20/phet/circuit-construction-kit-ac_en_phet.html has the canvas context save/restore fix.  It may fully address this problem.  It would be good to know if there are any sightings of this problem after these fixes before we do any of the other investigation.  @KatieWoe and @Nancy-Salpepi can you please keep your eyes peeled for this in dev.20 and later?

**Comment by Nancy-Salpepi** [comment] 2021-09-01 16:16
Using the new build, I produced a circuit which resulted in a loss of the voltage graph (while still showing current).
<img width="774" alt="Screen Shot 2021-09-01 at 11 46 40 AM" src="https://user-images.githubusercontent.com/87318828/131705475-1409bf9f-c65b-4a01-a357-2e2ade74b7f8.png">

I recorded the entire build of the circuit so that it would be easy to reproduce. I cut it into 2 parts:

https://drive.google.com/file/d/1ESsOqgjica0K3qCyCd0RzkTgxH6ytISu/view?usp=sharing

https://drive.google.com/file/d/1_zcKA7ajgnrJRLE7aYDKlWuXRayD71m3/view?usp=sharing

**Comment by Nancy-Salpepi** [comment] 2021-09-01 17:25
In this circuit, neither chart had a reading:

<img width="982" alt="Screen Shot 2021-09-01 at 1 14 26 PM" src="https://user-images.githubusercontent.com/87318828/131714959-4c70bfe5-111e-4644-afa2-ca5ab99f027a.png">

Steps to reproduce:
1. In the RLC screen, connect 3 batteries in series
2. Place inductor above the batteries, leaving space in between
3. Add wire to the left side of inductor
4. Add another wire to the first one and connect to the left battery
5. Add wire to the right side of inductor
6. Add lightbulb to that wire
7. Add wire that completes the circuit, connecting to the lightbulb first
8. Attach voltage and current charts as shown in screenshot above

**Comment by samreid** [comment] 2021-09-07 17:06
I reproduced the circuit in the prior comment, and also saw that there was no curve on the plot.  However, this was due to the data being out of range, and zooming out did reveal the data.  So that symptom seems different than the video in the top comment where there is a dot on the chart but no data following the dot.  If we can still reproduce that problem (dot but no line), then I'm inclined to revert to the svg implementation.  May be OK since we made many performance improvements elsewhere.  @Nancy-Salpepi and @KatieWoe do you still see symptoms of the "dot but no line" like in the top movie?

**Comment by Nancy-Salpepi** [comment] 2021-09-07 20:22
@samreid I tried many circuits over the last couple hours and I was unable to produce a graph with a moving dot but no line. It doesn't mean it isn't possible, but I wasn't able to replicate the original issue nor create a new one.

**Comment by samreid** [comment] 2021-09-07 21:29
Thanks, let's consider this closed for now but reopen if anybody experiences another sighting.  Closing.

**Closed by samreid** 2021-09-07 21:29 UTC
Labels: type:bug, status:ready-for-qa
