### ISSUE TITLE
CT the right hand side value must be a number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#697] opened 2021-05-06 15:37 UTC
```
circuit-construction-kit-ac : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620272831901%22%2C%22timestamp%22%3A1620276427640%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: the right-hand-side-value must be a number. Instead it was NaN
Error: Assertion failed: the right-hand-side-value must be a number. Instead it was NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/assert/js/assert.js:25:13)
at ModifiedNodalAnalysisCircuit.solve (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:355:17)
at DynamicCircuit.solvePropagate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:150:36)
at DynamicState.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:420:41)
at Object.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:162:30)
at TimestepSubdivisions.errorAcceptable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:87:25)
at TimestepSubdivisions.getTimestep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:71:20)
at TimestepSubdivisions.stepInTimeWithHistory (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:47:32)
at DynamicCircuit.solveWithSubdivisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:167:36)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:186:40)
id: Bayes Chrome
Snapshot from 5/5/2021, 9:47:11 PM

----------------------------------

circuit-construction-kit-ac : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620272831901%22%2C%22timestamp%22%3A1620289313780%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: the right-hand-side-value must be a number. Instead it was NaN
Error: Assertion failed: the right-hand-side-value must be a number. Instead it was NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/assert/js/assert.js:25:13)
at ModifiedNodalAnalysisCircuit.solve (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:355:17)
at DynamicCircuit.solvePropagate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:150:36)
at DynamicState.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:420:41)
at Object.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:162:30)
at TimestepSubdivisions.errorAcceptable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:89:26)
at TimestepSubdivisions.getTimestep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:71:20)
at TimestepSubdivisions.stepInTimeWithHistory (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:47:32)
at DynamicCircuit.solveWithSubdivisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/DynamicCircuit.js:167:36)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:186:40)
id: Bayes Chrome
Snapshot from 5/5/2021, 9:47:11 PM
```

**Comment by samreid** [comment] 2021-06-15 16:57
Closing as duplicate of https://github.com/phetsims/circuit-construction-kit-common/issues/694

**Closed by samreid** 2021-06-15 16:57 UTC
Labels: type:automated-testing
