### ISSUE TITLE
Charge not conserved in disconnected capacitor

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#776] opened 2021-11-09 21:45 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/736
When the capacitor is disconnected from a circuit, or only connected on one end, changing capacitance should not change the charge on a plate.

**Visuals**
![incorectcharge](https://user-images.githubusercontent.com/41024075/141009898-5b66f531-cfef-43be-a5b3-9ff05c3b95a6.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: AC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.48/phet/circuit-construction-kit-ac_all_phet.html
Version: 1.0.0-dev.48 2021-11-09 19:35:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment] 2021-11-10 00:06
Charge should be conserved here, so changing C should result in a change in V (Q=CV). Instead, it looks like the sim is maintaining a constant V and adjusting Q instead.

**Comment by samreid** [comment] 2021-11-11 20:43
We discussed this today, the rule we want to implement is: if the capacitor is not in a loop with any voltage source (including a 0 V battery), then it should follow the Q=CV rule, but only when the user is changing the capacitance.  Otherwise it follows the pre-existing rule.  The behavior in a loop with a voltage source already seems correct.

**Comment by samreid** [comment] 2021-11-12 17:53
This was not working correctly in Java either:

![Kapture 2021-11-12 at 10 52 27](https://user-images.githubusercontent.com/679486/141512414-014d8261-3266-439d-b180-3aa241028c5e.gif)

**Comment by samreid** [comment] 2021-11-12 19:51
I implemented a first draft in the commit.  Some notes:

* Since the only way the capacitance changes is through the user interface, there was no need for a "is it in a loop" guard.  Changing the capacitance for a capacitor in the loop appears (to me) to give reasonable behavior.  This should be verified.
* I change the voltage of the start and end vertex of the capacitor, and you can see the change in the voltmeter readout.
* My main question is if the newly computed voltage should "flow" elsewhere.  Right now it is limited to the start and end vertices of the capacitor.  For instance, I wasn't sure why the left capacitor voltage drop wasn't changing in this case:
* 
![Kapture 2021-11-12 at 12 50 41](https://user-images.githubusercontent.com/679486/141526472-9bf33456-ab84-4f3b-95fd-f8cd61973562.gif)

**Comment by samreid** [comment] 2021-11-12 19:59
@arouinfar and I confirmed the value flowed throughout the circuit as desired.

**Comment by samreid** [comment] 2021-11-18 21:18
We reviewed this in today's design meeting.  @ariel-phet wants to take a closer look.  Thanks!

**Comment by KatieWoe** [comment] 2021-11-19 23:20
Disconnecting the capacitor seems to switch which plates have which charges on master.
![bad](https://user-images.githubusercontent.com/41024075/142703254-dd4db4c4-76b6-4f25-b580-404cadf719fd.gif)

**Comment by ariel-phet** [comment] 2021-11-20 00:04
In addition in 1.0.0-dev.51 changing the capacitance of a charged capacitor switches the charge on the plates as well. 


https://user-images.githubusercontent.com/4051174/142705786-207b2075-2478-4748-bf6a-9e9db3fcc200.mp4

**Comment by samreid** [comment] 2021-11-22 00:01
This looks caused by https://github.com/phetsims/circuit-construction-kit-common/issues/784, I'll be addressing it there.

**Comment by samreid** [comment] 2021-11-22 19:45
There is a proposed fix for the sign error in https://github.com/phetsims/circuit-construction-kit-common/issues/784, but testing in this issue should probably hold off until that issue is checked.

**Comment by samreid** [comment] 2021-11-30 05:24
#784 is mostly in good shape, I think this can be checked now.

**Comment by arouinfar** [comment] 2021-11-30 17:34
@samreid I am unable to reproduce the behavior in https://github.com/phetsims/circuit-construction-kit-common/issues/776#issuecomment-974549502 and https://github.com/phetsims/circuit-construction-kit-common/issues/776#issuecomment-974535331 in dev.52.

**Comment by Nancy-Salpepi** [comment] 2021-12-01 13:16
@samreid I am unable to reproduce any of the above behavior in dev.53. Closing.

**Closed by Nancy-Salpepi** 2021-12-01 13:16 UTC
Labels: type:bug, priority:2-high, status:ready-for-review
