### ISSUE TITLE
Dead circuit elements after quick carousel interaction

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#426] opened 2017-10-20 20:42 UTC
@ariel-phet I'm thinking this is pretty device specific, but I'm hoping @samreid can help diagnose this issue to find the root cause and (hopefully) reproduce on all devices.

Reproducible on: Samsung Galaxy Tab A (so this might occur in our Android app).

Step:
1. Double tap on an item in the carousel. If nothing happened, try again.  You could also just tap as much as you want, you'll just hit this issue multiple times.

This results in a dead circuit element(s) hovering over the carousel. It cannot be interacted with, it cannot be snapped to, and it doesn't erase on a Reset All (sometimes it does erase at first, but "comes back" after further interaction). This biggest annoyance is that it can block users from dragging new items out of the carousel.

*Additionally, this seems performance related. This is easier for me to do with even a slight taxing of the tablet (like the circuit shown below).*

![cckdc25](https://user-images.githubusercontent.com/5863899/31840846-522fff5e-b5a4-11e7-9908-7a34222fe51b.gif)

This is not throwing an error. I CANNOT reproduce on any iPad.

For phetsims/QA/issues/55.
URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-rc.1/circuit-construction-kit-dc_en.html
Version: 1.0.0-rc.1 2017-10-17 18:05:58 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; SM-T580 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Safari/537.36
Language: en-US
Window: 1280x776
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 96)
Max viewport: 8192x8192
OES_texture_float: false
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"8a8ff7d2","branch":"HEAD"},"babel":{"sha":"0b5a4452","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"b8a3c09a","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"11736e99","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"5cbdc391","branch":"HEAD"},"dot":{"sha":"84bc5146","branch":"HEAD"},"joist":{"sha":"92b186e2","branch":"HEAD"},"kite":{"sha":"067109a8","branch":"HEAD"},"phet-core":{"sha":"054b2d6d","branch":"HEAD"},"phetcommon":{"sha":"b13138d2","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"c9c3052a","branch":"HEAD"},"scenery-phet":{"sha":"124c1c25","branch":"HEAD"},"sherpa":{"sha":"0d590744","branch":"HEAD"},"sun":{"sha":"082fee37","branch":"HEAD"},"tandem":{"sha":"98e9917c","branch":"HEAD"},"twixt":{"sha":"a2eaa10a","branch":"HEAD"}}

**Comment by ariel-phet** [comment] 2017-10-20 21:44
@samreid I would say this is very much "no bueno" considering we have the android app these days (and will want a CCK app in addition). Would be good to identify the bug and fix.

**Comment by phet-steele** [comment] 2017-10-20 21:53
@samreid @ariel-phet I can reproduce on touchscreen Chrome OS (but not with a cursor?).

**Comment by samreid** [comment] 2017-10-24 20:30
In the video, it looks like 2 light bulbs are created, and one of them disappears and the other becomes the zombie.

**Comment by samreid** [comment] 2017-10-25 03:40
@ariel-phet I implemented a feature in CCK which has the following behavior: when you tap and immediately release on an object in the control panel, the object stays on the screen for half a second before it disappears, see https://github.com/phetsims/circuit-construction-kit-common/issues/224

There is a good chance that the implementation leads to this issue (dead circuit elements) as a side effect.  I'll look to see if there is an obvious logic flaw, but one way out may be to revert https://github.com/phetsims/circuit-construction-kit-common/issues/224 and just hide circuit elements right away (let them "flicker").  Just raising it as a possibility in case my logic check doesn't lead to anything.

**Comment by samreid** [comment] 2017-10-25 03:46
It looks like there is invalid usage of setTimeout in CircuitElementNode.js, and I'm wondering if some platforms have a different behavior for setTimeout(0)--we could easily test with setTimeout(1) instead to test this hypothesis.

**Comment by samreid** [comment] 2017-10-25 20:03
Possible tests we can do:

1. try making sure the setTimeout minimum is 1 instead of 0
2. Use Timer.setTimeout instead of window.setTimeout
3. Get rid of the 500ms delay altogther

I'm leaning toward jumping all the way to (3) unless the design team @ariel-phet @arouinfar recommends otherwise.

**Comment by arouinfar** [comment] 2017-10-25 20:06
Option (3) is fine with me @samreid.

**Comment by samreid** [comment] 2017-10-25 20:12
Thanks @arouinfar.  I published a dev version here without any 500ms delay:

https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.167/circuit-construction-kit-dc_en.html

@phet-steele can you please test this on the devices that revealed problems?

**Comment by phet-steele** [comment] 2017-10-25 20:19
> @phet-steele can you please test this on the devices that revealed problems?

@samreid it's easier to break now.

**Comment by samreid** [comment] 2017-10-26 17:08
We added console.log to SimpleDragHandler in FixedCircuitElementNode and throughout SimpleDragHandler and are seeing that a start+move is happening with no end, even though the pointers have all been lifted.

<img width="830" alt="screen shot 2017-10-26 at 11 06 07 am" src="https://user-images.githubusercontent.com/679486/32066707-e881369c-ba3d-11e7-996e-c9e33405f408.png">

**Comment by samreid** [comment] 2017-10-26 17:08
@jessegreenberg and @phet-steele also identified this symptom is present in Projectile Motion

**Comment by samreid** [comment] 2017-10-26 17:10
We noticed that SimpleDragHandler.createForwardingListener supports down but not up, maybe this is related to the problem?

**Comment by samreid** [comment] 2017-10-26 21:41
@jonathanolson and @phet-steele are investigating in https://github.com/phetsims/scenery/issues/702

**Comment by samreid** [comment] 2017-10-27 04:26
@ariel-phet said that this issue does not need to be solved for 1.0.  However, if we publish 1.0 and find a non-invasive fix for this, we would be able to incorporate it easily as a maintenance release.  We'll continue in the scenery issue then re-evaluate for CCK after further progress.

**Comment by samreid** [comment] 2017-10-30 03:26
On hold until we hear back from https://github.com/phetsims/scenery/issues/702

**Comment by samreid** [comment] 2017-11-02 04:14
Unassigning myself until we know more

**Comment by WHWONTTHEDOGDIE** [comment] 2018-10-15 19:17
WHY WON'T THE DAMN DOG DIE I HAVE PUT OVER 1 MILLION VOLTS THROUGH IT AND IT STILL WONT DIE FFFFFFFUUUUUUUUUUUUUCCCCCCCCCCCCKKKKKKKKK

**Comment by ariel-phet** [comment] 2020-01-30 06:17
I attempted to reproduce on my android phone, both loading CCK in the browser, and through our Android app.

I see no evidence of this bug existing now, and if it does exist, it would seem not only difficult to reproduce but also an unusual user interaction. Considering we have also heard no bug reports from users to this effect, I am fine with closing.

**Closed** 2020-01-30 06:17 UTC
Labels: status:on-hold, type:bug
