### ISSUE TITLE
Pulling out different types of light bulbs leads to assertion error

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#958] opened 2023-02-08 01:23 UTC
Error message: `Assertion failed:  phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitNode.lightBulbNodeGroup.lightBulbNode_0`

To reproduce:
- Go to lab screen
- Add a regular light bulb to the stage
- Click 'Real bulbs'
- Add a real bulb to the stage

**Comment by matthew-blackman** [comment] 2023-02-08 01:25
Found while investigating https://github.com/phetsims/circuit-construction-kit-common/issues/957

Could this be related to https://github.com/phetsims/circuit-construction-kit-common/issues/630#issuecomment-1421527608 in https://github.com/phetsims/circuit-construction-kit-common/issues/630?

**Comment by matthew-blackman** [comment] 2023-02-08 17:31
@samreid @arouinfar and I agree that there should be a separate group for realLightBulbNodeGroup in the view, similar to how groups are being used for resistors, extremeResistors and householdObjects.

**Comment by arouinfar** [comment] 2023-02-08 20:14
Looks great, thanks!

**Comment by samreid** [comment] 2023-02-09 04:57
I found in Studio there was an extra bulb socket like so:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/679486/217721839-34294a41-a2f2-4fd9-bfad-5825cf4be470.png">

So I added the commits above which seemed to fix it.  Would be good to code review with @matthew-blackman.  And testing to make sure the correct circuit element groups still appear in the appropriate circumstances (lab screen vs intro screen, and ac vs dc).

**Comment by samreid** [comment] 2023-02-09 15:37
@matthew-blackman and I discovered phetioIsArchetype is `undefined` for 2 of the light bulb types on Screen 1.  We must find out the cause.

**Comment by samreid** [comment] 2023-02-09 16:12
The problem is that `PhetioObject.initializePhetioObject` has a guard and early return if `providedOptions.tandem.supplied` is false.  In this case, when we used the pattern of

```ts
    initializeCircuitElementType( ( e: CircuitElement ) => e instanceof LightBulb && e.isReal, this.fixedCircuitElementLayer,
      new PhetioGroup<CircuitElementNode, [ CircuitElement ]>( ( tandem: Tandem, circuitElement: CircuitElement ) => new CCKCLightBulbNode( screenView, this, circuitElement as LightBulb, this.model.isValueDepictionEnabledProperty, this.model.viewTypeProperty, tandem ),
        () => [ this.circuit.realLightBulbGroup.archetype ], {
          phetioType: PhetioGroup.PhetioGroupIO( Node.NodeIO ),
          tandem: circuit.includeLabElements ? tandem.createTandem( 'realLightBulbNodeGroup' ) : Tandem.OPT_OUT,
          supportsDynamicState: false
```

That part about `          tandem: circuit.includeLabElements ? tandem.createTandem( 'realLightBulbNodeGroup' ) : Tandem.OPT_OUT,` was creating a PhetioObject with a tandem that exists but is `supplied: false`.  Hence it never runs the `phetioIsArchetype` assignment.  Therefore, our solution that avoids creating these groups with `Tandem.OPT_OUT` is the correct solution.  Closing.

**Comment by samreid** [comment] 2023-02-10 16:24
Fixed an assertion error that a group appeared twice.  Closing.

**Closed by samreid** 2023-02-10 16:24 UTC
Labels: priority:2-high, status:ready-for-review
