### ISSUE TITLE
User reported issue: PDOM visible, interfering with use

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#684] opened 2021-03-23 16:46 UTC
![image](https://user-images.githubusercontent.com/5090275/112184526-e793b500-8bc4-11eb-94c5-eda781b97d70.png)

> I am having trouble getting the PHET simulation on Circuits to work properly. The site loads, but there is some text underneath that isn’t usually there. I am not able to drag any components (wire, battery, light bulb, etc) to the work mat to use the activity. I have attached a picture for your reference.
> 
> Troubleshooting information:
> !!!!! DO NOT EDIT !!!!!
> Name: ‪Circuit Construction Kit: DC
> URL: https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html
> Version: 1.2.1 2021-03-07 05:07:17 UTC
> Features missing: applicationcache, applicationcache, touch
> User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
> Language: en-US
> Window: 1680x907
> Pixel Ratio: 1/1
> WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
> GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
> Vendor: WebKit (WebKit WebGL)
> Vertex: attribs: 16 varying: 30 uniform: 4096
> Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
> Max viewport: 32767x32767
> OES_texture_float: true
> Dependencies JSON: {}

**Comment by oliver-phet** [comment] 2021-03-23 17:13
Additional screenshots:
![image](https://user-images.githubusercontent.com/5090275/112188399-91287580-8bc8-11eb-9993-1db82ca653af.png)
![image](https://user-images.githubusercontent.com/5090275/112188409-95ed2980-8bc8-11eb-9f51-6e928c695305.png)
![image](https://user-images.githubusercontent.com/5090275/112188430-9980b080-8bc8-11eb-8647-9461c7b9d20a.png)

@zepumph @jessegreenberg assigning to you per @samreid

**Comment by samreid** [comment] 2021-03-23 17:30
From the screenshots and user agent decoder, it seems the problem is showing on Win 10 + Chrome.

**Comment by samreid** [comment] 2021-03-23 17:37
I tested on my Win 10 + Chrome 89, but could not reproduce the problem.

**Comment by oliver-phet** [comment] 2021-03-23 17:39
If relevant, device is a Lenovo Yoga 260. It is a laptop and also flips into tablet mode.

**Comment by jessegreenberg** [comment] 2021-03-23 17:53
I also am unable to see this happen on my Win 10 + Chrome Version 89.0.4389.90 (Official Build) (64-bit).

**Comment by oliver-phet** [comment] 2021-03-23 18:13
@jessegreenberg Is there other information I could collect from the user to help diagnose this issue?

**Comment by jessegreenberg** [comment] 2021-03-23 20:29
It is behaving as though the PDOM isn't hidden at all with CSS. I am curious if stylesheets aren't working for the user (used by SceneryStyle.js). Otherwise, some very important CSS attribute in PDOMSiblingStyle.js is unsupported. Let me think a little and get back to you @oliver-phet.

**Comment by jessegreenberg** [comment] 2021-03-23 20:43
@zepumph tried on a Lenovo IdeaPad Flex 4 1470 in both laptop and tablet modes and wasn't able to see the problem.

**Comment by oliver-phet** [comment] 2021-03-23 21:00
@jessegreenberg I wonder if a Chrome extension could be breaking the normal CSS rules. I'm going to ask the user to test in an incognito window with any/all extensions disabled.

**Comment by jessegreenberg** [comment] 2021-03-23 21:03
Thanks @oliver-phet, we were wondering about that too. The other thing we were wondering about is if there there are any error reports in the user's dev tools if they can open it.

Meanwhile, I am going to search for any known platform/error reports related to https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule, and the attributes used in PDOMSiblingStyle.

**Comment by oliver-phet** [comment] 2021-03-23 22:00
@jessegreenberg @zepumph you can stop investigating!

> I figured it out!!! It’s the Screen Shader Chrome extension! Once I turn it off, the simulation works just fine. Thanks so much for all your help!!!

**Comment by samreid** [comment] 2021-03-24 14:51
I don't want to belabor this issue unnecessarily, but I thought we should reflect and decide whether we want to pursue any of the following avenues:

a) Should we try to understand why the Screen Shader Chrome extension caused this problem?
b) Should we try to make our implementation compatible with this extension?
c) Should we try to understand whether other extensions may suffer from similar symptoms?
d) Should we document this problem (on a FAQ or troubleshooting page), so that it can be shared to users with this problem in the future?

We can open side issues as appropriate, or re-close this issue if we decide not to pursue any.  @jessegreenberg and @zepumph can you please recommend how to proceed?

**Comment by jessegreenberg** [comment] 2021-03-24 15:50
I just tried the Screen Shader Chrome extension and it still worked on my Win 10 machine. I played around with settings for a while and didn't see this issue. It works by adding elements to the very top of the z-order that take up the whole screen and act as a filter over everything else. That should be compatible with the PDOM. However, if this addon or any other directly modifies styles it could break things. I am wondering if an older version of Screen Shader did that.

I think a troubleshooting item that suggests disabling browser extensions could be helpful. @oliver-phet does that seem reasonable and where should that go?

**Comment by oliver-phet** [comment] 2021-03-24 15:53
Yep, I started drafting the help center entry yesterday and will get it published later today. This is only the second or third time over the years a user has written in about a problem caused by an extension. I don't think this seems common enough with our users to warrant further investigation on our part.

**Comment by jessegreenberg** [comment] 2021-03-24 15:58
OK, thanks. I think that is sufficient for this issue. @samreid back to you to review or recommend if anything more should be done.

**Comment by samreid** [comment] 2021-03-24 16:06
I also tried out Screen Shader in Mac Chrome and tried a variety of settings and could not reproduce the problem.  I think this issue can be closed, unless @oliver-phet wants to use it to track publishing the help center entry.  Up to you!

**Closed** 2021-03-24 16:10 UTC
Labels: type:user-feedback

**Comment by jessegreenberg** [comment] 2021-10-12 18:34
Sounds good, I am going to move this to scenery. Currently I still suspect that an extension or user setting is modifying/disabling CSS.
