### ISSUE TITLE
CT phetioID already registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#871] opened 2022-02-28 16:43 UTC
```
circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646047221053%22%2C%22timestamp%22%3A1646049080148%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitNode.lightBulbNodeGroup.lightBulbNode_9
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitNode.lightBulbNodeGroup.lightBulbNode_9
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/phet-io/js/phetioEngine.js:616:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/phet-io/js/phetioEngine.js:1107:20)
at DynamicTandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/tandem/js/Tandem.js:156:36)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/tandem/js/PhetioObject.js:241:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/scenery/js/nodes/Node.js:6058:11)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/scenery/js/nodes/Node.js:6037:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/scenery/js/nodes/Node.js:498:12)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/circuit-construction-kit-common/js/view/CircuitElementNode.js:41:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646047221053/chipper/dist/js/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:57:5)
id: Bayes Chrome
Snapshot from 2/28/2022, 4:20:21 AM
```

**Comment by samreid** [comment] 2022-03-09 22:37
I'm not able to reproduce this locally at the moment, closing for now.

**Closed by samreid** 2022-03-09 22:37 UTC
Labels: type:automated-testing
