### ISSUE TITLE
Scale is wrong

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#300] opened 2017-05-04 21:24 UTC
Drag out resistor.  Zoom out.  Reset.  Drag out resistor.  It is too big!  Same problem for voltmeter and ammeter.

Thanks @Denz1994

**Comment by samreid** [comment] 2017-05-08 17:39
Proposed fix is above, @Denz1994 can you please pull and verify?

**Comment by Denz1994** [comment] 2017-05-08 18:11
I checked out a previous version and did side-by-side comparison to the latest version.
 
![image](https://cloud.githubusercontent.com/assets/13894380/25818254/3e42ce02-33e7-11e7-9482-c2e3f62df259.png)

left screen = latest sha
right screen =  commit a3a0a49

They changes you made fixed the problem and I cannot reproduce the bug. Closing

**Closed by Denz1994** 2017-05-08 18:11 UTC
Labels: status:ready-to-test
