### ISSUE TITLE
With DC offsets readings on current and voltage chart can appear blank

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#759] opened 2021-10-19 04:27 UTC
If you set up an AC circuit with a sufficient DC offset the current and voltage charts can appear blank at their default zoom. It seems we should have some way to indicate to the user that the reading is off-scale or potentially consider autoscaling in the case where no readout is being shown.  Here is an example:

https://user-images.githubusercontent.com/4051174/137843865-7bc34132-fa41-4ea4-868c-81920cbf34d3.mp4

Noticed during https://github.com/phetsims/circuit-construction-kit-common/issues/748

**Comment by arouinfar** [comment] 2021-10-19 22:40
Thanks @ariel-phet. I've definitely run into situations where it took me a bit to realize that I had off-scale data. I would personally love it if these graphs would autoscale. Autoscale would have the added benefit of removing the zoom buttons and trimming the tool body down a bit. However, it's probably more complicated than we want right now.

An alternative would be to display a message like "Data out of range" or possibly just "Out of range" if there isn't at least some data visible within the chart. Here's a rough mockup
![image](https://user-images.githubusercontent.com/8419308/138000308-7064b511-99c1-4193-b22b-a7f743172d8a.png)

What do you think @ariel-phet?

**Comment by samreid** [comment] 2021-11-04 21:26
Today, we decided that if all of the data is 100% out of range, we will show a message "Data out of range".  We like the red text because it pops and kind of indicates an error.

**Comment by samreid** [comment] 2021-11-07 03:29
Implemented and ready for testing in next verison.

**Comment by arouinfar** [comment] 2021-11-07 23:55
@samreid this is generally looking good, but I noticed an inconsistency when the value is null vs. zero.

Steps to reproduce:
1. Build a simple circuit with 120 V battery and 120 ohm resistor.
2. Measure voltage and current with the chart tools. "Data out of range" message will appear, as expected.
3. Remove probe so that reading is zero. "Data out of range" persists but the dot has returned to zero (value is null).
4. Return probes to circuit. When "Data out of range" message pops up, set battery voltage to zero. The  "Data out of range" message will immediately disappear.

I think the behavior in (4) when the value is zero is preferable. Can you do the same for a null value @samreid?

**Comment by samreid** [comment] 2021-11-08 15:41
I adjusted the logic so that the message won't appear when the pen is showing at y=0.  Will be ready for review in next dev version.

**Comment by samreid** [comment] 2021-11-08 20:44
@arouinfar can you please test in this version? https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.46/phet/circuit-construction-kit-ac_en_phet.html

**Comment by samreid** [comment] 2021-11-15 18:08
@arouinfar and I reviewed this today, and agreed the new behavior is good, closing.

**Closed by samreid** 2021-11-15 18:08 UTC
Labels: status:ready-for-review, design:polish
