### ISSUE TITLE
Circuit with switch and capacitor leads to bad performance, potential loss of items

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/circuit-construction-kit-common#695] opened 2021-04-26 22:58 UTC
### Test Device

MacBook Air

### Operating System

macOS 11.2.3

### Browser

Safari 14.0.3

### Problem Description

Noticed while testing on master (https://github.com/phetsims/circuit-construction-kit-ac/commit/90e7d3e71157f9e8aeda8773e142c04c207a6a68). If you create a circuit like the one below and you try to use the switch, the sim will slow down significantly. It won't crash the sim, but the sim becomes unusable for a few seconds.

I've witnessed all elements of my circuit "fly away" (not sure how else to phrase it) when playing with the switch of the below circuit. I noticed this error in the console:

```
[Error] Error: Assertion failed: Cannot add the same listener twice
	(anonymous function) (assert.js:25)
	addListener (TinyEmitter.js:114)
	addListener (Emitter.js:83)
	(anonymous function) (soundManager.js:272)
	(anonymous function) (audioContextStateChangeMonitor.js:47)
	forEach
	(anonymous function) (audioContextStateChangeMonitor.js:46)
```

### Steps to Reproduce

1. Create the below circuit.
2. Attempt to use switch.

### Visuals

![circuit](https://user-images.githubusercontent.com/60749003/116161193-93db2680-a6b0-11eb-906e-06caec5f9505.png)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: Circuit Construction Kit: AC
URL: https://bayes.colorado.edu/dev/phettest/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?ea&brand=phet
Version: 1.0.0-dev.14 (unbuilt)
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
Language: en-us
Window: 1440x820
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

</details>

**Comment by samreid** [comment] 2021-04-30 16:38
This could be tracked with https://github.com/phetsims/QA/issues/646

**Comment by samreid** [comment] 2021-06-15 16:56
I was able to reproduce the problem.  It seems the problem is due to the extreme nonlinearity in the resistance-less capacitor-closed-switch circuit.  `getTimestep` cannot find a small enough `dt` that linearizes the system, so `errorAcceptable` and `getTimestep` are called many times until we reach the minimum threshold.

Some ideas for how to solve this:
* Model a tiny resistor in series with each capacitor?  What problem would this cause?
* Change the threshold for nonlinear search?  But it was already tuned low enough to suppress other problems
* Other ideas?

@arouinfar can you please review and advise?

**Comment by samreid** [comment] 2021-07-29 20:37
@ariel-phet suggests checking the wires to make sure they have resistance

@kathy-phet reminded us that we went to a very small resistance in the wire in a recent issue.

We would like to try adding a small resistance in series with the capacitor to see if that helps.  We will start with a small value and increase it until it helps.

**Comment by samreid** [comment] 2021-08-14 01:35
There is a chance that the error in the matrix algorithm identified in https://github.com/phetsims/circuit-construction-kit-common/issues/693#issuecomment-898694052 may solve this problem.  I recommend we investigate it first before adding the series resistance for this case.

**Comment by samreid** [comment] 2021-08-16 19:31
The fix in https://github.com/phetsims/circuit-construction-kit-common/issues/693 did not address this problem, so let's proceed with a small resistance in series with the capacitor.

**Comment by samreid** [comment] 2021-08-16 21:24
This patch should add resistance to the capacitor, but it doesn't work as expected.  

<details>

```js
Index: js/model/DynamicCircuit.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/DynamicCircuit.js b/js/model/DynamicCircuit.js
--- a/js/model/DynamicCircuit.js	(revision 7a4cf9b74103e7e8b928fd830db8557d23110f1e)
+++ b/js/model/DynamicCircuit.js	(date 1629148907980)
@@ -103,7 +103,7 @@
       const companionVoltage = capacitorAdapter.state.voltage - companionResistance * capacitorAdapter.state.current;
 
       const battery = new ModifiedNodalAnalysisCircuitElement( capacitorAdapter.dynamicCircuitCapacitor.nodeId0, newNode, null, companionVoltage );
-      const resistor = new ModifiedNodalAnalysisCircuitElement( newNode, capacitorAdapter.dynamicCircuitCapacitor.nodeId1, null, companionResistance );
+      const resistor = new ModifiedNodalAnalysisCircuitElement( newNode, capacitorAdapter.dynamicCircuitCapacitor.nodeId1, null, companionResistance + 10 );
       companionBatteries.push( battery );
       companionResistors.push( resistor );
 ```
</details>

**Comment by samreid** [comment] 2021-08-25 09:39
First, I saw that `dt` is subdivided, so using a constant term for the added resistance doesn't make sense.  I added that feature and it still didn't work.  I hypothesized that since the companion voltage takes values from `capacitorAdapter.state`, we couldn't include the resistor in that part, but when I added it as a separate part, it had the same problem:

<details>

```diff
Index: js/model/DynamicCircuit.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/DynamicCircuit.js b/js/model/DynamicCircuit.js
--- a/js/model/DynamicCircuit.js	(revision 30b2fd14c839e8f3246515df978068039b31dd90)
+++ b/js/model/DynamicCircuit.js	(date 1629884299934)
@@ -90,10 +90,14 @@
       assert && assert( capacitorAdapter.dynamicCircuitCapacitor.capacitance >= 0, 'capacitance should be non-negative' );
       assert && assert( dt >= 0, 'dt should be non-negative' );
 
-      const newNode = _.max( usedNodes ) + 1;
-      usedNodes.push( newNode );
+      const newNode1 = _.max( usedNodes ) + 1;
+      usedNodes.push( newNode1 );
+
+      const newNode2 = _.max( usedNodes ) + 1;
+      usedNodes.push( newNode2 );
 
       const companionResistance = dt / 2.0 / capacitorAdapter.dynamicCircuitCapacitor.capacitance;
+      const resistanceTerm = 625 * dt;
 
       // The capacitor is modeled as a battery in series with a resistor.  Hence the voltage drop across the capacitor
       // is equal to the voltage drop across the battery plus the voltage drop across the resistor.
@@ -102,10 +106,14 @@
       // |V|=|IReq| and sign is unchanged since the conventional current flows from high to low voltage.
       const companionVoltage = capacitorAdapter.state.voltage - companionResistance * capacitorAdapter.state.current;
 
-      const battery = new ModifiedNodalAnalysisCircuitElement( capacitorAdapter.dynamicCircuitCapacitor.nodeId0, newNode, null, companionVoltage );
-      const resistor = new ModifiedNodalAnalysisCircuitElement( newNode, capacitorAdapter.dynamicCircuitCapacitor.nodeId1, null, companionResistance );
+      const battery = new ModifiedNodalAnalysisCircuitElement( capacitorAdapter.dynamicCircuitCapacitor.nodeId0, newNode1, null, companionVoltage );
+      const resistor = new ModifiedNodalAnalysisCircuitElement( newNode1, newNode2, null, companionResistance );
+      const resistor2 = new ModifiedNodalAnalysisCircuitElement( newNode2, capacitorAdapter.dynamicCircuitCapacitor.nodeId1, null, resistanceTerm );
+
+      console.log( dt, companionResistance, resistanceTerm );
       companionBatteries.push( battery );
       companionResistors.push( resistor );
+      companionResistors.push( resistor2 );
 
       // We need to be able to get the current for this component. In series, so the current is the same through both.
       currentCompanions.push( {
Index: js/model/ModifiedNodalAnalysisCircuit.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/ModifiedNodalAnalysisCircuit.js b/js/model/ModifiedNodalAnalysisCircuit.js
--- a/js/model/ModifiedNodalAnalysisCircuit.js	(revision 30b2fd14c839e8f3246515df978068039b31dd90)
+++ b/js/model/ModifiedNodalAnalysisCircuit.js	(date 1629884060850)
@@ -72,10 +72,9 @@
    */
   toString() {
     if ( assert ) { // stripped out for builds
-      return `resistors:${this.resistors.map( resistorToString ).join( ',' )}, ` +
-             `batteries: ${this.batteries.map( batteryToString ).join( ',' )}, ` +
-             `currentSources: ${this.currentSources.map( c => c.toString() )
-               .join( ',' )}`;
+      return `resistors:\n${this.resistors.map( resistorToString ).join( '\n' )}\n` +
+             `batteries:\n${this.batteries.map( batteryToString ).join( '\n' )}\n` +
+             `currentSources:\n${this.currentSources.map( c => c.toString() ).join( '\n' )}`;
     }
     else {
       return 'toString() only defined when assertions are enabled';

```

</details>

**Comment by samreid** [comment] 2021-08-25 10:29
Here is a patch that uses the correct intermediate nodes for computing that node voltage, and a TODO for one other spot that will need to compute the mnaVoltage without including the auxiliary resistor:

<details>

```diff

Index: js/model/ModifiedNodalAnalysisAdapter.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/ModifiedNodalAnalysisAdapter.js b/js/model/ModifiedNodalAnalysisAdapter.js
--- a/js/model/ModifiedNodalAnalysisAdapter.js	(revision 30b2fd14c839e8f3246515df978068039b31dd90)
+++ b/js/model/ModifiedNodalAnalysisAdapter.js	(date 1629887273771)
@@ -105,7 +105,7 @@
   applySolution( circuitResult ) {
     this.capacitor.currentProperty.value = circuitResult.getTimeAverageCurrent( this.dynamicCircuitCapacitor );
     this.capacitor.mnaCurrent = circuitResult.getInstantaneousCurrent( this.dynamicCircuitCapacitor );
-    this.capacitor.mnaVoltageDrop = circuitResult.getInstantaneousVoltage( this.dynamicCircuitCapacitor );
+    this.capacitor.mnaVoltageDrop = circuitResult.getInstantaneousVoltage( this.dynamicCircuitCapacitor ); // TODO: don't read the auxiliary resistor
     assert && assert( Math.abs( this.capacitor.mnaCurrent ) < 1E100, 'mnaCurrent out of range' );
     assert && assert( Math.abs( this.capacitor.mnaVoltageDrop ) < 1E100, 'mnaVoltageDrop out of range' );
   }
Index: js/model/DynamicCircuit.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/DynamicCircuit.js b/js/model/DynamicCircuit.js
--- a/js/model/DynamicCircuit.js	(revision 30b2fd14c839e8f3246515df978068039b31dd90)
+++ b/js/model/DynamicCircuit.js	(date 1629886755244)
@@ -90,10 +90,14 @@
       assert && assert( capacitorAdapter.dynamicCircuitCapacitor.capacitance >= 0, 'capacitance should be non-negative' );
       assert && assert( dt >= 0, 'dt should be non-negative' );
 
-      const newNode = _.max( usedNodes ) + 1;
-      usedNodes.push( newNode );
+      const newNode1 = _.max( usedNodes ) + 1;
+      usedNodes.push( newNode1 );
+
+      const newNode2 = _.max( usedNodes ) + 1;
+      usedNodes.push( newNode2 );
 
       const companionResistance = dt / 2.0 / capacitorAdapter.dynamicCircuitCapacitor.capacitance;
+      const resistanceTerm = 625 * dt;
 
       // The capacitor is modeled as a battery in series with a resistor.  Hence the voltage drop across the capacitor
       // is equal to the voltage drop across the battery plus the voltage drop across the resistor.
@@ -102,10 +106,21 @@
       // |V|=|IReq| and sign is unchanged since the conventional current flows from high to low voltage.
       const companionVoltage = capacitorAdapter.state.voltage - companionResistance * capacitorAdapter.state.current;
 
-      const battery = new ModifiedNodalAnalysisCircuitElement( capacitorAdapter.dynamicCircuitCapacitor.nodeId0, newNode, null, companionVoltage );
-      const resistor = new ModifiedNodalAnalysisCircuitElement( newNode, capacitorAdapter.dynamicCircuitCapacitor.nodeId1, null, companionResistance );
+      const battery = new ModifiedNodalAnalysisCircuitElement( capacitorAdapter.dynamicCircuitCapacitor.nodeId0, newNode1, null, companionVoltage );
+      const resistor = new ModifiedNodalAnalysisCircuitElement( newNode1, newNode2, null, companionResistance );
+      const resistor2 = new ModifiedNodalAnalysisCircuitElement( newNode2, capacitorAdapter.dynamicCircuitCapacitor.nodeId1, null, resistanceTerm );
+
+      console.log( dt, companionResistance, resistanceTerm );
       companionBatteries.push( battery );
       companionResistors.push( resistor );
+      companionResistors.push( resistor2 );
+
+      capacitorAdapter.voltageReadout0 = capacitorAdapter.dynamicCircuitCapacitor.nodeId0;
+      capacitorAdapter.voltageReadout1 = newNode2;
+
+      // capacitorAdapter.bat = battery;
+      // capacitorAdapter.res1 = resistor;
+      // capacitorAdapter.res2 = resistor2;
 
       // We need to be able to get the current for this component. In series, so the current is the same through both.
       currentCompanions.push( {
@@ -214,7 +229,7 @@
   updateCircuit( solution ) {
     const updatedCapacitors = this.capacitorAdapters.map( capacitorAdapter => {
       const newState = new DynamicElementState(
-        solution.getNodeVoltage( capacitorAdapter.dynamicCircuitCapacitor.nodeId1 ) - solution.getNodeVoltage( capacitorAdapter.dynamicCircuitCapacitor.nodeId0 ),
+        solution.getNodeVoltage( capacitorAdapter.voltageReadout1 ) - solution.getNodeVoltage( capacitorAdapter.voltageReadout0 ),
         solution.getCurrent( capacitorAdapter )
       );
       return new DynamicCapacitor( capacitorAdapter.dynamicCircuitCapacitor, newState );
Index: js/model/ModifiedNodalAnalysisCircuit.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/ModifiedNodalAnalysisCircuit.js b/js/model/ModifiedNodalAnalysisCircuit.js
--- a/js/model/ModifiedNodalAnalysisCircuit.js	(revision 30b2fd14c839e8f3246515df978068039b31dd90)
+++ b/js/model/ModifiedNodalAnalysisCircuit.js	(date 1629885798617)
@@ -72,10 +72,9 @@
    */
   toString() {
     if ( assert ) { // stripped out for builds
-      return `resistors:${this.resistors.map( resistorToString ).join( ',' )}, ` +
-             `batteries: ${this.batteries.map( batteryToString ).join( ',' )}, ` +
-             `currentSources: ${this.currentSources.map( c => c.toString() )
-               .join( ',' )}`;
+      return `resistors:\n${this.resistors.map( resistorToString ).join( '\n' )}\n` +
+             `batteries:\n${this.batteries.map( batteryToString ).join( '\n' )}\n` +
+             `currentSources:\n${this.currentSources.map( c => c.toString() ).join( '\n' )}`;
     }
     else {
       return 'toString() only defined when assertions are enabled';

```

</details>

**Comment by samreid** [comment] 2021-08-25 11:14
I found that the downstream fixes meant the series resistance should not be a function of dt after all.  I committed this draft since it is what we were aiming for, but it has the following problems:

1. Behavior for the circuit in the top comment is still somewhat chunky (better than before, but even at `?capacitorResistance=1` it still stutters
2. Now the capacitor doesn't clear out, even when it seems it should be chargeless, it has a +/-.  I'm not sure if this is a bug in the physics or something expected that we will have to work around.  Still, I'd rather get feedback on this proposal before investigating that part.

![image](https://user-images.githubusercontent.com/679486/130780752-a5480d95-eb0f-42e7-8056-1119135d88be.png)

Please note I put the default value for `capacitorResistance` as `1E-6` the same as the value for the battery.

**Comment by samreid** [comment] 2021-08-28 01:05
This fix also appears in https://github.com/phetsims/circuit-construction-kit-common/issues/721.  @KatieWoe can you please have the QA team test a variety of circumstances like the problematic ones in this issue, and some variations?  Please use https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.16/phet/circuit-construction-kit-ac_en_phet.html for testing.

**Comment by Nancy-Salpepi** [comment] 2021-09-10 15:37
@samreid on the MacBook 11.4 + chrome, this is what the circuit now looks like:
![issue695dev24](https://user-images.githubusercontent.com/87318828/132879756-d6f2a577-9e17-476f-8ad0-bbc90f1eac6d.gif)

**Comment by samreid** [comment] 2021-09-10 20:06
@arouinfar should that circuit read out the battery voltage, or the voltage from traversing the wires (0 V)?

**Comment by Nancy-Salpepi** [comment] 2021-09-16 15:53
In addition to my question in https://github.com/phetsims/circuit-construction-kit-common/issues/695#issuecomment-916998453
@arouinfar I was also wondering if it is correct for the electrons to only be moving around the bottom half of the circuit?

![electronlocation](https://user-images.githubusercontent.com/87318828/133644510-bf88f1de-3f31-4993-8f54-53b5478bba29.gif)

**Comment by samreid** [comment] 2021-09-16 15:55
We recently added resistance across the capacitor, so that probably explains why the current is only running in the bottom part.  Wires have resistance too, much it is much lower than the capacitor resistance.

**Comment by samreid** [comment] 2021-09-16 20:38
In today's design meeting, we confirmed the battery voltage is reduced when shorted, so the voltage readout is correct.  @ariel-phet confirmed the current flowing through the short circuit is correct.  We decided to close this issue.  @arouinfar reviewed the teacher tips for these concepts.

**Closed by samreid** 2021-09-16 20:38 UTC
Labels: status:ready-for-qa
