### ISSUE TITLE
Increase number of voltage/current charts to 2

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#643] opened 2021-01-05 19:23 UTC
We currently only have one of each chart type, but two voltmeters and non-contact ammeters. At first I thought this was a mistake, but it looks like we made the decision in https://github.com/phetsims/circuit-construction-kit-common/issues/518#issuecomment-538118656 to only allow one of each chart type. For comparison, Java has an unlimited number (which is certainly more than necessary).

I'd like to revisit this decision. Having two of each chart type would allow students to make comparisons between circuits, and more easily see the differences in frequency and phase. 

What do you think @ariel-phet @kathy-phet @samreid?

**Comment by ariel-phet** [comment] 2021-01-05 20:00
I would be fine with 2 of each. It has the potential to get pretty crowded, but that is up to the user.

**Comment by kathy-phet** [comment] 2021-01-05 20:22
I'm fine with 2 of each as well!

**Comment by samreid** [comment] 2021-01-05 20:25
Sounds good to me! I think we are unanimous, so I'll self-assign and mark this for the AC milestone.

**Comment by samreid** [comment] 2021-01-06 03:26
I increased the maximum to 2 current charts and 2 voltage charts, and this is ready for review.  I thought in one run, I saw the 2 voltage charts out-of-phase, but I was unable to replicate the problem.  @arouinfar can you please test?

**Comment by arouinfar** [comment] 2021-01-06 22:43
@samreid I didn't see any issues with the phase of the voltage charts, but I did run into an issue with the current sign. I created two simple AC circuits (AC source + default resistor) and the current charts showed opposite polarities. The circuits were otherwise identical.

**Comment by samreid** [comment] 2021-01-12 03:22
Thanks for the report @arouinfar, I was able to reproduce this problem:

![image](https://user-images.githubusercontent.com/679486/104265085-10bbfa80-544a-11eb-8050-2f8810ea4293.png)

This problem occurs because the sign "sense" or directionality of the current is chosen when the circuit is closed.  If you complete the 2nd circuit when the 1st circuit is positive, they will have the same sense:

![image](https://user-images.githubusercontent.com/679486/104265163-3943f480-544a-11eb-825e-3c984222c94d.png)

We may be constrained about how we determine the current sign based on the solution in https://github.com/phetsims/circuit-construction-kit-common/issues/622#issuecomment-749814222.  @arouinfar can you please advise?

**Comment by samreid** [comment] 2021-03-04 21:11
We'll continue this last topic in https://github.com/phetsims/circuit-construction-kit-common/issues/678, closing.

**Closed by samreid** 2021-03-04 21:11 UTC
Labels: design:general, status:ready-for-review
