### ISSUE TITLE
Turn off sounds for most items

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#562] opened 2020-01-16 17:30 UTC
@samreid I believe the tambo works currently is that once you turn on sound, it is on for everything, on the lastest version "common" sounds are on for all buttons. Sims like CCK probably need a full sound design before we start using default sounds for common components (fine to leave the sound for the reset all button).

You should see how much effort it is to turn off these other sounds, and we might want to request the @jbphet change the current default in tambo. I believe @Denz1994 had to do the same for BAM, and I don't think it was much effort, but it would be good to have another data point.

**Comment by samreid** [comment] 2020-01-16 17:33
@Denz1994 or @jbphet can you please advise how this can be accomplished?

**Comment by Denz1994** [comment] 2020-01-16 17:45
@samreid In most cases, I have been able to pass in an option for `soundPlayer` like this:
 ```
// Add button
      const button = new TextPushButton( nextCollectionString, {
        font: new PhetFont( {
          size: 18,
          weight: 'bold',
          maxWidth: BAMConstants.TEXT_MAX_WIDTH
        } ),
        baseColor: Color.ORANGE,
        soundPlayer: Playable.NO_SOUND
      } );
```
This does mean that tambo was added as a dependency for the sim, but the process was reletively straightforward.

**Comment by Denz1994** [comment] 2020-01-16 17:48
Also note @samreid, for classes whose options weren't exposed (due to composition or nesting). I had to go ahead and expose the options. Details are explained in https://github.com/phetsims/sun/issues/547.

Unassigning until further input is needed.

**Comment by samreid** [comment] 2020-01-16 23:41
It does not seem practical to have to pass `soundPlayer: Playable.NO_SOUND` to numerous user interface components.  @jbphet is there a better "shut off valve" for this?

**Comment by samreid** [comment] 2020-01-17 00:15
Bumping priority in hopes to address this before Jan 23 dev release.

**Comment by jbphet** [comment] 2020-01-17 17:12
I discussed this with @ariel-phet when common UI sounds were first integrated into master, and at the time we decided that using `soundPlayer.NO_SOUND` was a reasonable solution.  @Denz1994 did it for Build a Molecule and didn't raise any objections.  If this isn't working for you, then my suggestion would be that we tag all of the UI sounds as belonging to the `user-interface` class, and then turn that class all the way down.  

Let me know which, if either, you'd prefer and we can work together to make it happen.

**Comment by samreid** [comment] 2020-01-17 17:14
@ariel-phet or @kathy-phet is this important to complete before next week's dev version?

**Comment by samreid** [comment] 2020-01-18 15:30
Specifying `Playable.NO_SOUND` in many places doesn't sound scalable.  For instance, `Playable.NO_SOUND` occurs in 10 different places across 8 files in Build a Molecule, and if a new user interface component is added, there is a chance that this option would be omitted.  I would recommend we pursue an alternate strategy.  Let's discuss further!

**Comment by samreid** [comment] 2020-01-18 15:38
I tried `soundManager.setOutputLevelForClass( 'user-interface', 0 );` but it looks like some or all user interface sounds are not set up with that class.  What would work well for CCK AC is to say "only sounds with class ``sim-specific`` should play", that way there is no opportunity for a sound to sneak in.  Is something like that possible?

**Comment by jbphet** [comment] 2020-01-20 19:32
I put all of the common UI sounds into the `user-interface` category and added a line to code to set the output level for these sounds to zero to CCK AC.  This solves the issue that @samreid was describing, at least as well as I understand it.  Back to @samreid for review.

**Comment by ariel-phet** [comment] 2020-01-21 17:10
@samreid this is not a requirement for the dev version you were asked to publish. As I mentioned, I just think this sim would require a full sound design before considering if the common component sounds work well with the rest of the simulation. I don't believe sound design is expected for V1, so it seems appropriate to turn these sounds off (except the reset all button).

**Comment by samreid** [comment] 2020-01-21 17:23
It seems in CCK AC, it is impossible to generate 0.1 amps through the dog. The dog has a resistance of 100,000 ohms and the battery has a max voltage of 120V, so it would take around 83 batteries (n = 100000*0.1/120) to make the dog bark.  I don't know of any plans to add high-voltage batteries to this sim, so perhaps we should disable the sound altogether?  That way the speaker icon on the navigation bar won't be shown, and there won't be any possibility of single UI sound clips sneaking in.  But in the preceding comment, it sounded like @ariel-phet favored the reset all button sound effect.

I recommend to disable all sound from CCK AC and to use the strategy @jbphet proposed for CCK DC when it is published again.  @ariel-phet does this sound OK to you?

**Comment by ariel-phet** [comment] 2020-01-22 07:14
@samreid - I am fine with that for CCK AC, but CCK DC will be able to have the dog bark, so as long as the proposal works for a future update of CCK DC, I am fine going that route for the moment.

**Comment by samreid** [comment] 2020-07-27 17:08
For #589 @kathy-phet said:

> Well, we haven't done a sound review. Is it possible to disable all common code sound, but leave the dog?
> It's odd to have things like the carousel make sound, but not all the other sounds like picking up and dropping this and such.

I'll increase the priority and follow the recommendation above.

**Comment by samreid** [comment] 2020-07-27 18:05
I applied this strategy to CCK DC and verified that sounds only play for the dog bark.  If more common code sounds creep in, we will need to make sure they are labeled as "user-interface".  That's everything for this issue, closing.

**Comment by arouinfar** [comment] 2021-01-15 19:35
@samreid this will need to be done in the DC - Virtual Lab flavor too. Currently, all user-interface sounds are present in master.

**Comment by samreid** [comment] 2021-01-19 17:55
Fixed and confirmed on my side, @arouinfar can you please test?

**Comment by arouinfar** [comment] 2021-01-19 18:18
👍🏻

**Closed by arouinfar** 2021-01-19 18:18 UTC
Labels: dev:a11y, status:ready-for-review
