### ISSUE TITLE
meterNode visibleProperty for model and view causing buggy behavior

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#951] opened 2023-01-25 13:47 UTC
For the ammeter and voltmeter nodes, there are two visibleProperties: both view and model.

model visibleProperty: false puts the tool back into the toolbox. visibleProperty: true restores the tool back to its previous position in the play area. This is consistent with other sims.

@arouinfar @samreid and I agree that we should rename this isActiveProperty (follows Projectile Motion and MSAB pattern) and uninstrument the view visibleProperty for meters.

**Comment by AgustinVallejo** [comment] 2023-01-25 14:06
Will take a look!

**Comment by matthew-blackman** [comment] 2023-01-30 18:21
Note: Review model.meters phet io overrides after this issue is complete. We will want to feature activeProperty on the meters.

**Comment by matthew-blackman** [comment] 2023-01-31 16:02
@arouinfar this is ready for us to review in the tree

**Comment by samreid** [comment] 2023-02-02 02:03
I reviewed the commits and tested in studio.  Everything seems great here.  Sounds like @arouinfar and @matthew-blackman may need to check on the tree and possibly phet-io-overrides.  Reassigning.

**Comment by arouinfar** [comment] 2023-02-03 21:05
Something's not quite right with `isActiveProperty`. If both voltmeters are active in the play area, the "Voltmeter" label is hidden in the toolbox.  This a change from the published version, and looks a bit odd.

| Master | Latest Published Version | 
| --- | --- | 
|  ![image](https://user-images.githubusercontent.com/8419308/216710058-d4c40a03-a711-4db6-997f-dc01d4d6e5ea.png) | ![image](https://user-images.githubusercontent.com/8419308/216709985-39152269-5d01-4d1d-b891-2fc52ecad3ca.png) |

What's stranger is that completely removing all series ammeters leaves behind a ghost, similar to the strategy we employ for carousel. This creates an inconsistent appearance:
![image](https://user-images.githubusercontent.com/8419308/216710235-6fa38b46-e5a0-43f2-a619-2604a9aabd0d.png)

Back to @matthew-blackman.

**Comment by samreid** [comment] 2023-02-05 03:39
Before deciding how to proceed for this issue, I'd like to discuss part of the implementation and design.  It's nice to reuse the circuit element tool code for the ammeter, but it has the default behavior of leaving behind the ghost.  If we liked having the ghost in the carousel, would we also like to have ghosts in the sensor toolbox?  I'm not sure what will be easier--unghosting the series ammeter or ghosting the other element.  But thought I should ask before starting.  Or should we just implement whatever seems easier? Or is it OK that they are inconsistent, because one is a circuit element and the other is not?

It seems in either case we would need to fix the voltmeters text.  So perhaps I'll start there.

**Comment by samreid** [comment] 2023-02-05 03:52
It was straightforward to zero out the series ammeter ghost transparency.  So I did that, and I tried to retain the text when all items are dragged out (but not when tools are made invisible from studio).  Most things seem to be good, but there may be a corner case or two that is not consistent?  @arouinfar or @matthew-blackman can you please help test?

**Comment by arouinfar** [comment] 2023-02-06 05:47
> It was straightforward to zero out the series ammeter ghost transparency. So I did that, and I tried to retain the text when all items are dragged out (but not when tools are made invisible from studio). 

Great! While the ghosting looks nice for the carousel, it seems odd in the toolbox. Overall, things are looking good.

> Most things seem to be good, but there may be a corner case or two that is not consistent?

There's some strange behavior with dynamic layout that I don't love because it exposes resizing panels to the users.

* On the Intro Screen, take both non-contact ammeters meters out of the toolbox, and the toolbox will get shorter.
* On the Lab Screen, take both non-contact ammeters out of the toolbox. The series ammeter will recenter over the "Ammeter" label and the entire panel will get narrower. The same does not happen when series ammeters are all in the play area and there is still a non-contact ammeter left in the toolbox.

Additionally, using `isActiveProperty` to remove the voltmeters from the toolbox looks odd. Everything ends up centered in the play area, including the probes.
<img width="136" alt="image" src="https://user-images.githubusercontent.com/8419308/216892809-664d4cff-3750-47a8-bd12-3e5e6c4068d5.png">

 It would be preferable if the probes could look like this:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/8419308/216893014-4e7cfae7-fdb0-4aa4-9892-da189232b3f6.png">

**Comment by samreid** [comment] 2023-02-06 10:17
Thanks, I was able to reproduce those 3 errant behaviors and correct them with the commits.  Can you please test/verify?

**Comment by arouinfar** [comment] 2023-02-06 22:05
Thanks @samreid, looks good!

**Closed by arouinfar** 2023-02-06 22:05 UTC
Labels: status:ready-for-review
