### ISSUE TITLE
Opening and closing switch while paused causes current to jump from negative to positive

### ISSUE THREAD

**Issue by stemilymill** [phetsims/circuit-construction-kit-common#778] opened 2021-11-11 19:47 UTC
For https://github.com/phetsims/qa/issues/736, also may be related to https://github.com/phetsims/circuit-construction-kit-common/issues/770.
When opening and closing a switch while sim is paused, current in one part of a circuit jumps to zero and back to the original value, but current in another part of a circuit jumps from its original (negative) value to zero and then to a positive value.

https://user-images.githubusercontent.com/85511101/141358320-75ebc6fe-38d5-4480-9ff0-8aecc52fd6ce.mp4

**Comment by KatieWoe** [comment] 2021-11-11 19:50
I was able to reproduce this with a fairly simple circuit. If the current was positive when the switch turned off, it will be positive again when turned on and the curve looks smooth. If it was negative however, it is positive when turned back on.
![simplecircuitsignchange](https://user-images.githubusercontent.com/41024075/141359917-3e242419-3bfa-4edf-ba00-4e257af480b7.gif)

**Comment by KatieWoe** [comment] 2021-11-11 19:53
May be related to https://github.com/phetsims/circuit-construction-kit-common/issues/606

**Comment by KatieWoe** [comment] 2021-11-11 20:18
@samreid I also noticed that the sign the current reads depends on when the first ammeter was dragged out.
1. Build a circuit with a battery, lightbulb, and wires.
2. Pull out an ammeter and look at the current
3. Switch the battery around and observe the negative current.
4. Hit reset all
5. Build the circuit from step 3
6. Pull out the ammeter and observe

**Comment by samreid** [comment] 2021-11-12 20:59
For https://github.com/phetsims/circuit-construction-kit-common/issues/778#issue-1051306559, I think the behavior is as expected, please see https://github.com/phetsims/circuit-construction-kit-common/issues/770#issuecomment-967534803

For https://github.com/phetsims/circuit-construction-kit-common/issues/778#issuecomment-966579897, there is a rule that the first reading from a completed circuit should be positive.  I think that explains the sign change.  

For https://github.com/phetsims/circuit-construction-kit-common/issues/778#issuecomment-966597173, I am seeing the expected behavior, that the current is positive on the first reading on a completed circuit.  Are you seeing something different?

**Comment by samreid** [comment] 2021-11-15 18:17
@arouinfar and I reviewed the 3 cases above and all the behavior seems to be expected.  @arouinfar will check the teacher tips to make sure it discusses that the initial currents are always positive (no matter the direction of the battery).  You will see the polarity flip if you flip the battery after connection, but not before.

**Comment by KatieWoe** [comment] 2021-11-15 18:21
@samreid this is what I'm seeing. I can get it to read negative first, but it might be explained by what you said in https://github.com/phetsims/circuit-construction-kit-common/issues/778#issuecomment-969187094
![contradiction](https://user-images.githubusercontent.com/41024075/141833792-2133db4c-09d9-46b6-a5e4-de7b787eee8d.gif)

**Comment by samreid** [comment] 2021-11-15 23:38
@arouinfar and I reviewed the behavior, and agreed it is the expected behavior.  The current directionality is selected to make initial currents positive at the time the circuit is completed..

**Comment by samreid** [comment] 2021-11-18 21:32
At today's design meeting, we discussed that it is confusing for the current to change direction when a switch is opened then closed.  @kathy-phet asked if I could investigate that.  Fixing this is not critical for 1.0, but I'll investigate.

The current (pun!) rule is:

```js
// Disconnected circuits have a current of exactly 0, so we can use that to determine when to clear the sense
    const isReadyToClear = current === 0;
```

We could change the rule to "current is zero and it is not in a loop with an open switch".  We would at least like to try that much before 1.0.

**Comment by samreid** [comment] 2021-11-23 22:31
> @kathy-phet asked if I could investigate that. Fixing this is not critical for 1.0, but I'll investigate.

The existing depth-first search algorithms have special handling around switches (to not traverse them) and do not track which elements were traversed, so it would take 2-4 hours to write out this new algorithm and test it thoroughly. I'm not sure whether this is acceptable, especially if it's on the longer side.  @arouinfar @kathy-phet @ariel-phet want me to keep working on this for 1.0?

**Comment by kathy-phet** [comment] 2021-11-23 22:55
I vote for deferring this exploration until after 1.0 is published. When we do PhET-iO, we can revisit this issue, but proceed with with publishing the current behavior.

**Comment by ariel-phet** [comment] 2021-11-24 21:27
I concur with @kathy-phet -- @samreid probably should mark this issue deferred on on-hold.

**Comment by samreid** [comment] 2021-12-23 20:24
On hold until we address the phet-io specific issues.

**Comment by samreid** [comment] 2022-01-24 17:01
@arouinfar indicated that there are no current signs in DC, so this may be able to wait until we publish AC.

**Comment by samreid** [comment] 2022-01-28 17:06
@arouinfar should we label the current milestone as "dc-specific", and remove this from the milestone?

**Comment by samreid** [comment] 2022-01-28 19:23
@kathy-phet said this does not need to be part of the client preview milestone.  @arouinfar confirmed that pause is irrelevant to this issue.

**Comment by samreid** [comment] 2022-02-18 21:13
> @kathy-phet recommends the design team reviews the current algorithm before @samreid rewrites anything.

@arouinfar how should we accomplish that step?

**Comment by arouinfar** [comment] 2022-11-30 19:53
Self-assigning to understand the current behavior.

**Comment by matthew-blackman** [comment] 2022-12-15 21:05
12/15/22 Design Meeting

We agree that this is an issue worth spending about 4-8 hours working on since it is related to pedagogical needs. It is not a top priority for this Initial PhET-iO DC release milestone, but should be moved to the Initial PhET-iO AC release milestone.

The behavior of the non-contact ammeter is consistent and described within documentation, but this is still worth a couple hours of investigation for the AC edge cases.

@matthew-blackman will investigate if there are remaining edge cases within DC that could have pedagogical ramifications.

**Comment by matthew-blackman** [comment] 2022-12-19 20:20
@samreid and I implemented a possible fix by having circuit components remember their 'currentSense' even when disconnected. This fixes the issue, but could have potential drawbacks. For example, if a new set of students sat down to a sim that was already open, they could be confused as to why the initial current reading was negative. We will also need to check for issues with taking components from one circuit and placing them in another.

**Comment by samreid** [comment] 2023-02-13 22:53
@arouinfar can you please review and advise?

**Comment by matthew-blackman** [comment] 2023-02-14 16:23
@samreid and I agree that this behavior is acceptable, but should be clearly documented. We will look into the documentation files that are presented to the user and how this can be best communicated through those files.

@arouinfar can you advise the appropriate place to document this?

**Comment by arouinfar** [comment] 2023-03-06 23:56
I agree that the behavior is acceptable. It is well-documented in the Teacher Tips, but I did make some updates to the AC Tips and the DC Tips (will upload in #886).  I think we can go ahead and close this issue. Short of moving to ngspice (#228), I don't think we'll make any further major changes to the circuit dynamics.

**Closed by arouinfar** 2023-03-06 23:56 UTC
Labels: meeting:design
